import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import Provider from "./provider";


const AppFont = DM_Sans({
  subsets: ["latin"],
  // weight: ["400", "500", "700"],
  // variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "AI Code Box - Your AI Coding Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={AppFont.className}
      >
        <Provider>
            {children}
         </Provider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
